/**
 * Image Proxy Routes
 *
 * Proxies Gradio file URLs (e.g. `/gradio_api/file=<path>`) so the client can
 * access images generated by HuggingFace Spaces / ModelScope without being
 * blocked by Gradio 6.20.0+ SSRF-safe proxy or ephemeral file cleanup.
 *
 * The API layer (Cloudflare Workers) fetches the image on behalf of the client,
 * using the same IP that initiated the generation request.
 */

import { Errors, isAllowedProxyHost, isGradioFileUrl } from '@z-image/shared'
import { Hono } from 'hono'
import { rateLimitPresets, sendError } from '../middleware'

export const proxyRoutes = new Hono()

proxyRoutes.use('/*', rateLimitPresets.readonly)

proxyRoutes.get('/image', async (c) => {
  const rawUrl = c.req.query('url')
  if (!rawUrl) {
    return sendError(c, Errors.invalidParams('url', 'Missing url query parameter'))
  }

  // Parse and validate the URL
  let parsed: URL
  try {
    parsed = new URL(rawUrl)
  } catch {
    return sendError(c, Errors.invalidParams('url', 'Invalid url format'))
  }

  // SSRF protection: only allow known Gradio-serving hosts
  if (!isAllowedProxyHost(parsed.hostname)) {
    return sendError(c, Errors.invalidParams('url', `Host not allowed: ${parsed.hostname}`))
  }

  // Only proxy Gradio file URLs
  if (!isGradioFileUrl(rawUrl)) {
    return sendError(c, Errors.invalidParams('url', 'Only Gradio file URLs are supported'))
  }

  try {
    const upstream = await fetch(rawUrl)
    if (!upstream.ok) {
      return sendError(
        c,
        Errors.providerError('Proxy', `Upstream returned HTTP ${upstream.status}`)
      )
    }

    // Stream the response body through with appropriate headers
    const headers = new Headers()
    headers.set(
      'Content-Type',
      upstream.headers.get('content-type') || 'image/png'
    )
    headers.set('Content-Length', upstream.headers.get('content-length') || '')
    // Cache the proxied image for 1h on the client/CDN. Gradio temp files
    // eventually expire, but short-lived caching is safe and improves perf.
    headers.set('Cache-Control', 'public, max-age=3600')

    return new Response(upstream.body, { headers })
  } catch {
    return sendError(c, Errors.providerError('Proxy', 'Failed to fetch upstream image'))
  }
})
